[package]
name = "fastest-fibo"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
rayon = "1.10.0"

[dependencies.rug]
version = "1.27.0"
default-features = false
features = ["integer", "float"]

[profile.release]
# lto = true
# opt-level = 3
